###
get http://127.0.0.1:3001/




###
get http://127.0.0.1:3001/api/news/getNewsList
###
get http://127.0.0.1:3001/api/news/getNewsList?title=世界
###
get http://127.0.0.1:3001/api/news/getNewsList?type=9


###
get http://127.0.0.1:3001/api/news/getNewsCategory


###
get http://127.0.0.1:3001/api/news/getNewsDetail/68


###
post http://127.0.0.1:3001/api/news/newsPub
Content-Type: application/json
Authorization: {{token}}


###
post http://127.0.0.1:3001/api/news/newsDel
Content-Type: application/json
Authorization: {{token}}

{
    "id": 85
}


###
get http://127.0.0.1:3001/api/guidePage/getGuidePageCarouselImages

###
get http://127.0.0.1:3001/api/carousel/getCarouselImages

###
get http://127.0.0.1:3001/api/carousel/getPic/e614cb7f-63b0-4cda-bf47-db286ea1b074

###
post http://127.0.0.1:3001/api/carousel/uploadImages

### 
post http://127.0.0.1:3001/api/user/register
Content-Type: application/json

{
    "username": "user3",
    "password": "333333"
}


###
# @name login
post http://127.0.0.1:3001/api/user/login
Content-Type: application/json

{
    "username": "user3",
    "password": "333333"
}


###
get http://127.0.0.1:3001/api/user/getUserInfo
Content-Type: application/json
Authorization: {{token}}


###
post http://127.0.0.1:3001/api/user/updateUserPassword
Content-Type: application/json
Authorization: {{token}}

{
    "oldPassword": "abaaba",
    "newPassword": "444444"
}



### variables
@token = {{login.response.body.token}}
